name: Build ghostlock‑pfem10
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout源码
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装基础依赖
        run: sudo apt update && sudo apt install -y build-essential make

      - name: 安装Android NDK r25c
        uses: Ylarod/setup-ndk-clang@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: 设置NDK环境变量，执行build.sh编译
        run: |
          export NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          chmod +x build.sh
          ./build.sh

      - name: 上传编译产物ghostlock
        uses: actions/upload-artifact@v4
        with:
          name: ghostlock‑pfem10
          path: ghostlock
